# Generated by Django 4.2.16 on 2024-11-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="price",
            field=models.CharField(max_length=100, null=True, verbose_name="猫咪价格"),
        ),
        migrations.AlterField(
            model_name="cat",
            name="description",
            field=models.CharField(max_length=250, verbose_name="猫咪简介"),
        ),
        migrations.AlterField(
            model_name="cat",
            name="image",
            field=models.ImageField(upload_to="cat/images/", verbose_name="猫咪照片"),
        ),
        migrations.AlterField(
            model_name="cat",
            name="title",
            field=models.CharField(max_length=100, verbose_name="猫咪品种"),
        ),
        migrations.AlterField(
            model_name="cat",
            name="url",
            field=models.URLField(blank=True, verbose_name="猫猫资源"),
        ),
    ]
