# Generated by Django 4.2.16 on 2024-11-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat", "0002_cat_price_alter_cat_description_alter_cat_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cat",
            options={"verbose_name": "猫咪", "verbose_name_plural": "猫咪"},
        ),
    ]
