# Generated by Django 4.2.16 on 2024-11-21 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cat", "0004_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cat",
            options={},
        ),
        migrations.AlterField(
            model_name="review",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cat_reviews",
                to="cat.cat",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cat_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
