# Generated by Django 4.2.16 on 2024-11-21 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cat", "0006_alter_review_cat_alter_review_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cat.cat"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
